Requirements
SinisterBBT/StringConcatCourse pull request #1
Opened 2021-05-02 19:04 UTC by SinisterBBT

2021-05-03 09:55 UTC, elukianov requested changes

2021-05-03 09:55 UTC, elukianov commented on 1_requirements.md
> +[Miro](https://miro.com/welcomeonboard/SJJiPa91ZtS9ww7e7D5vj9pUPTv8cEWw0wEDc05DUC8oTqNgmJCYY0up0TZOVVhb)
Кажется тут ссылка кривая

2021-05-03 09:56 UTC, SinisterBBT commented on 1_requirements.md
> +[Miro](https://miro.com/welcomeonboard/SJJiPa91ZtS9ww7e7D5vj9pUPTv8cEWw0wEDc05DUC8oTqNgmJCYY0up0TZOVVhb)
https://miro.com/welcomeonboard/SJJiPa91ZtS9ww7e7D5vj9pUPTv8cEWw0wEDc05DUC8oTqNgmJCYY0up0TZOVVhb

2021-05-03 09:57 UTC, SinisterBBT commented on 1_requirements.md
> +[Miro](https://miro.com/welcomeonboard/SJJiPa91ZtS9ww7e7D5vj9pUPTv8cEWw0wEDc05DUC8oTqNgmJCYY0up0TZOVVhb)
вроде работает со второго аккаунта

2021-05-03 09:58 UTC, SinisterBBT commented on 1_requirements.md
> +[Miro](https://miro.com/welcomeonboard/SJJiPa91ZtS9ww7e7D5vj9pUPTv8cEWw0wEDc05DUC8oTqNgmJCYY0up0TZOVVhb)
что именно не так? права или доску вообще не находит?

2021-05-03 10:36 UTC, SinisterBBT commented on 1_requirements.md
> +[Miro](https://miro.com/welcomeonboard/SJJiPa91ZtS9ww7e7D5vj9pUPTv8cEWw0wEDc05DUC8oTqNgmJCYY0up0TZOVVhb)
Возможно вот эта будет лучше
https://miro.com/app/board/o9J_lG6VzeI=/

2021-05-03 10:37 UTC, SinisterBBT commented on 1_requirements.md
> +[Miro](https://miro.com/welcomeonboard/SJJiPa91ZtS9ww7e7D5vj9pUPTv8cEWw0wEDc05DUC8oTqNgmJCYY0up0TZOVVhb)
эта линка для всех view-only, но тогда комменты оставлять не получится прямо на доске

2021-05-05 07:52 UTC, elukianov commented
Всё круто, только пару комметариев. 

1) Лучше убрать формулировку "Может", так формулировки будут чище и короче. 

2) Клиент может искать и сортировать рейсы - я бы разделил эти 2 истории, потому что они поиск возможен и без сортировки и наоборот.

2021-05-05 07:52 UTC, merged