Use cases flight management and maintenance
SinisterBBT/StringConcatCourse pull request #11
Opened 2021-08-24 07:51 UTC by SinisterBBT

2021-08-27 13:06 UTC, elukianov requested changes

2021-08-27 13:06 UTC, elukianov commented on detekt/detekt-config.yml
> +    max: 4
Подозрительно!

2021-08-27 13:06 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/aircraft/Aircraft.kt
> +        fun receiveNewAircraftInfo(
А почему Info вдруг?

2021-08-27 13:06 UTC, elukianov commented on flightManagement/usecase/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/usecase/order/CreateOrderUseCase.kt
> +    override fun execute(request: CreateOrderRequest): Either<CreateOrderCaseError, Order> =
Я бы тут ещё клиента отправил на оплату

2021-08-27 13:06 UTC, elukianov commented on flightManagement/usecase/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/usecase/flight/AnnounceNewFlightUseCase.kt
> +    override fun execute(request: AnnounceNewFlightRequest): Either<AnnounceNewFlightCaseError, Flight> =
Тут и везде я вижу из метода возвращается прям таки доменный объект. Так вцелом делать можно, но это может быть опасно (но пока можно и так оставить, если что поправим). Кто-нибудь дернет метод у Flight, а он у нас в ин-мемори лежит. Можно просто id вернуть к примеру

2021-08-27 13:11 UTC, schomework requested changes
Не с той учотки случайно отправил

2021-08-28 15:43 UTC, SinisterBBT commented on flightManagement/usecase/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/usecase/flight/AnnounceNewFlightUseCase.kt
> +    override fun execute(request: AnnounceNewFlightRequest): Either<AnnounceNewFlightCaseError, Flight> =
Переделать вроде не сложно, но тогда оставлю пока. Почему опасно - понимаю.

2021-08-28 15:45 UTC, SinisterBBT commented on detekt/detekt-config.yml
> +    max: 4
Как я и писал - все из-за CreateOrderRequest. Возможно я просто не очень уверенно себя чувствую с Either и всей этой функциональщиной, но другого способа, кроме как возвращать каждую ошибку по отдельности я не нашел.

2021-08-28 16:18 UTC, SinisterBBT commented on flightManagement/usecase/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/usecase/flight/AnnounceNewFlightUseCase.kt
> +    override fun execute(request: AnnounceNewFlightRequest): Either<AnnounceNewFlightCaseError, Flight> =
Хотя с другой стороны - не понимаю. Они же immutable.

2021-09-10 13:19 UTC, schomework commented on flightManagement/usecase/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/usecase/flight/AnnounceNewFlightUseCase.kt
> +    override fun execute(request: AnnounceNewFlightRequest): Either<AnnounceNewFlightCaseError, Flight> =
В этом конкретном случае да, неизменяемый. Но вот к примеру  там где заказы - они изменяемые. Пока давай так оставим, переделывать долго будет сейчас

2021-09-10 13:20 UTC, schomework approved these changes
Неси зачётку

2021-09-11 09:05 UTC, merged