Implementation of the maintenance and flight management domain contexts
SinisterBBT/StringConcatCourse pull request #9
Opened 2021-07-19 10:07 UTC by SinisterBBT

2021-07-20 12:01 UTC, elukianov requested changes

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/aircraft/AircraftModel.kt
> +class AircraftModel internal constructor(val value: String) : ValueObject {
Если это VO, то должено быть сравнение по значению, а здесь этого нет. Видимо пропущен тест на эквивалентность. Намекаю на то, что нет ключевого слова data

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/aircraft/AircraftRegistrationNumber.kt
> +    companion object {
Аналогично с эквивалентностью, рекомендую проверить все оставшиется VO

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/aircraft/AircraftSeatMap.kt
> +class AircraftSeatMap internal constructor(val seatMap: ArrayList<Seat>) : ValueObject {
А действительно ли в этом контексте нужен SeatMap? Там в комментариях я писал что самолеты идут в компоновке эконом. В билете только есть рейс и цена. То есть фактически нам нужно только количество мест

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/flight/AircraftIsAlreadyInFlightChecker.kt
> +interface AircraftIsAlreadyInFlightChecker {
Можно AircraftIsAlreadyInFlight назвать, без суфикса. Тогда будет по красоте AircraftIsAlreadyInFlight.check. Но это уже так, на вкус имхо

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/flight/Flight.kt
> +    val aircraft: Aircraft,
Выходит ты ссылаешься на другой агрегат напрямую, а не через id, что не есть хорошо.

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Fio.kt
> +class Fio internal constructor(val fio: String) : ValueObject {
FullName)

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +    fun confirm() = changeState(OrderState.CONFIRMED, OrderConfirmedDomainEvent(id))
У нас в модели нет таких статусов и методов

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/OrderItem.kt
> +class OrderItem internal constructor(val passenger: Passenger, val ticket: Ticket) : ValueObject {
Прямая ссылка на агрегат из VO

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +            return if (orderItems.isNotEmpty()) {
А как мы проверим, что билет ещё не занят?

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/ticket/Price.kt
> +class Price(
data

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/ticket/Ticket.kt
> +    val flight: Flight,
Ссылка на агрегат

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/ticket/FlightIsToSoonForPublishingChecker.kt
> +interface FlightIsToSoonForPublishingChecker {
Имплементацию можно прям в домене забабахать, я писал про это в чятике группы

2021-07-20 12:01 UTC, elukianov commented on flightManagement/domain/src/test/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/PassportDataTest.kt
> +        val passportData = "1111 1111111"
А если другой формат будет типа 11111 222 - не сломается?

2021-07-20 12:01 UTC, elukianov commented on mainApp/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/configuration/FlightManagementConfiguration.kt
> +class FlightManagementConfiguration
Можно даже повыразительнее называть FlightManagementContextConfiguration

2021-07-20 12:01 UTC, elukianov commented on maintenance/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/maintenance/domain/flight/ActualArrivalAirport.kt
> +class ActualArrivalAirport internal constructor(val iataCode: String) : ValueObject {
Я бы вынес Аэропорт как общий VO. Он выглядит просто как какая-то метка на карте, не имеет обособленого поведения в контекстах, поэтому на данном этапе можно вынести

2021-07-20 12:01 UTC, elukianov commented on maintenance/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/maintenance/domain/flight/Flight.kt
> +    fun complete() = changeState(FlightState.COMPLETED, FlightCompletedDomainEvent(id))
Рейс прибыл, а не закончен. И пусть нам диспетчерская служба аэропорта передает количество часов налёта.

2021-07-20 21:26 UTC, SinisterBBT commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +            return if (orderItems.isNotEmpty()) {
Идея была в том, что если мы не можем вычитать билет в UseCase значит мы не сможем вызвать метод. Но видимо очевиднее реализовать это через TicketAvailable чекер.

2021-07-20 21:30 UTC, SinisterBBT commented on flightManagement/domain/src/test/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/PassportDataTest.kt
> +        val passportData = "1111 1111111"
нет сломается. Исходил из того что и не должно валидироваться никак кроме isNotBlank. Могу сделать валидацию по  length и пробелу в нужном месте или вообще разделить серию и номер.

2021-07-20 21:31 UTC, SinisterBBT commented on flightManagement/domain/src/test/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/PassportDataTest.kt
> +        val passportData = "1111 1111111"
В тз про валидацию ничего нет - можно отправить заказчика дописывать это в виде стори на следующий спринт =)

2021-07-20 21:35 UTC, SinisterBBT commented on maintenance/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/maintenance/domain/flight/ActualArrivalAirport.kt
> +class ActualArrivalAirport internal constructor(val iataCode: String) : ValueObject {
У меня была идея в будущем хранить в аэропорте его timeZone для вычислений всяких связанных с временем прибытия и тп. Это, как мне кажется, довольно логичный аттрибут для аэропорта. В этом случае, возможно, выносить как общий не стоит. Как ты думаешь?

2021-07-20 22:34 UTC, SinisterBBT commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/OrderItem.kt
> +class OrderItem internal constructor(val passenger: Passenger, val ticket: Ticket) : ValueObject {
Требуется замена на TicketId?

2021-07-20 22:46 UTC, SinisterBBT commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +    fun confirm() = changeState(OrderState.CONFIRMED, OrderConfirmedDomainEvent(id))
Я предположил, что это не методы модели, а стейт-машина свойственная для любого payment-провайдера. Если это не так - удалю все кроме WAITING_FOR_PAYMENT и COMPLETED

2021-07-23 08:04 UTC, elukianov requested changes
Думал уже всё готово)

2021-07-23 10:46 UTC, SinisterBBT commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/ticket/FlightIsToSoonForPublishingChecker.kt
> +interface FlightIsToSoonForPublishingChecker {
Копирую вопрос из телеги: "Жень, я так и не нашел в чате как можно сделать валидацию правила FlightIsToSoonForPublishing. Проблема в том, что мы не знаем когда Flight, у нас есть только его id. + даже если бы мы знали время отправления и могли сравнить его с now(), то непонятно какую именно зону текущего времени использовать для корректного сравнения."

2021-07-23 10:53 UTC, SinisterBBT commented on maintenance/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/maintenance/domain/flight/ActualArrivalAirport.kt
> +class ActualArrivalAirport internal constructor(val iataCode: String) : ValueObject {
+ Если выносить Airport то мы получается объединяем в один VO DepartureAirport и ArrivalAirport из flightManagement и ActualArrivalAirport из maintenance - т.е. каждая из этих штук это действительно просто точка на карте, но смысл у этих точек у каждой разный. Не лучше ли это выделить в виде разных VO?

2021-07-23 13:14 UTC, SinisterBBT commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +            return if (orderItems.isNotEmpty()) {
Решил добавить пояснение: Для создания OrderItem нам нужен ticketId. Если мы не можем предоставить ticketId, значит не можем создать и OrderItem

2021-07-26 09:21 UTC, elukianov requested changes

2021-07-26 09:21 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/aircraft/AircraftSeatCount.kt
> +object WrongSeatMapCount : BusinessError
Придирка: может быть WrongSeatCount?

2021-07-26 09:21 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/aircraft/AircraftSeatCount.kt
> +data class AircraftSeatCount internal constructor(val seatCount: Int) : ValueObject {
Вообще такие объекты типа Count можно выносить и в какой-нибудь commons

2021-07-26 09:21 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +    fun confirm() = changeState(OrderState.CONFIRMED, OrderConfirmedDomainEvent(id))
Как раз прикол в том, что мы не делаем предположение и пилим абстрактного провайдера. Если мы договорились, что это работает именно таким образом, то так тому и быть

2021-07-26 09:21 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +            return if (orderItems.isNotEmpty()) {
Тогда такой вопрос. Кто отвечает за предоставление этого ticketId? Если мы в 2 заказа захотим добавить один билет, то как будет это выглядеть?

2021-07-26 09:21 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/flight/ArrivalDate.kt
> +        fun from(arrivalDate: ZonedDateTime): Either<ArrivalDateToSoonError, ArrivalDate> {
Обратил внимание на эти ArrivalDate и DepartureDate. Немного не понятно, почему здесь ограничение в один час? Я думаю это ограничение должно быть немного в другом месте. Если хочется проверить диапазон, что одна дата меньше другой, то можно их заключить в VO, либо же при создании агрегата проверять

2021-07-26 09:21 UTC, elukianov commented on flightManagement/domain/src/test/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/PassportDataTest.kt
> +        val passportData = "1111 1111111"
А, ну если так) Просто из теста не очень понятно было что допустимо, а что нет

2021-07-26 09:21 UTC, elukianov commented on maintenance/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/maintenance/domain/flight/ActualArrivalAirport.kt
> +class ActualArrivalAirport internal constructor(val iataCode: String) : ValueObject {
Вообще можно и TZ аэропорта зафиксировать прям в VO, но думаю пока не стоит. По поводу зависимости от порядка. Такое действительно может быть, но можно попробовать сделать VO типа Route, где есть начало и конец, это может помочь. Есть такие типы, где правда можно напутать, типа Point(int, int), что уж тут поделать. + можно добавить typealias. Думаю ничего страшного тут нет, если потом будут проблемы - можно ввести. Если бы их было штук 5, вот тогда да

2021-07-26 09:21 UTC, elukianov commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/ticket/FlightIsToSoonForPublishingChecker.kt
> +interface FlightIsToSoonForPublishingChecker {
В чятике я писал про то, где должна быть реализация правил - в UC или же домене, это вот про это) Мы можем на вход принять Flight, посмотреть его время, посмотреть сколько сейчас время и сравнить. У нас же оно хранится в виде абсолютного времени

2021-07-30 17:38 UTC, SinisterBBT commented on flightManagement/domain/src/main/kotlin/com/polyakovworkbox/stringconcatcourse/flightManagement/domain/order/Order.kt
> +            return if (orderItems.isNotEmpty()) {
Ну насколько я понимаю, UC слой при создании пользователем заказа вытягивает свободный тикет из базы или где они у нас хранятся - если свободных тикетов нет - возвращает ошибку.
Я вижу кейс добавления одного и того же тикета в два заказа невалидным, так как тикет после того, как его не оплатили - должен вернуться в пул свободных и только тогда он может быть добавлен в другой заказ. Иначе может получиться, что у нас 2 клиента оплатили один и тот же билет.

2021-08-06 11:59 UTC, merged